version: '2'
services:

  flask:
    build:
      context: flask-server
      dockerfile: Dockerfile
    container_name: flask-atlas
    image: flask-atlas:latest
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./flask-server:/var/www
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb-atlas
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: <username>
      MONGO_INITDB_ROOT_PASSWORD: <password>
    ports:
      - 27017:27017
    volumes:
      - /srv/vc_mongodb:/data/db
