version: '2'
services:

  flask:
    build:
      context: flask-server
      dockerfile: Dockerfile
    container_name: flask-atlas
    image: flask-atlas:latest
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./flask-server:/var/www
    networks:
      - flask-api
networks:
  flask-api:
    name: atlas-project-network